[[Conduit]]
arch = "aarch64"
git-tree-sha1 = "67a017aba36484637da211ac69345d7d7d06f256"
os = "macos"

    [[Conduit.download]]
    sha256 = "6fa3d4182e7517be9c069ca8c6730604b59c8938394ac3f06b174c5b9a8212c7"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.aarch64-apple-darwin.tar.gz"
[[Conduit]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "81eefe722208913b99596fd04f23c42213cc0eda"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "6967cb746577d937fa0ab06739662147cb05b131cabb415c46088896f1b4071b"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.aarch64-linux-gnu-cxx03.tar.gz"
[[Conduit]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b761df7a5f22d1fe5591dc38be8a13383198dcdc"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "8a848fe2217e855e8a431dd1b9c97571fd761a63431af6bc97ff5e1748a03e06"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.aarch64-linux-gnu-cxx11.tar.gz"
[[Conduit]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b9dc14b110fb7745e1e5e8321119cfd254e358a"
libc = "musl"
os = "linux"

    [[Conduit.download]]
    sha256 = "e97bdc684512e1bf22db5fca6921d9a90d3c3ec00446cd2e9056d58e4115d0c4"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.aarch64-linux-musl-cxx03.tar.gz"
[[Conduit]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e909163297dab017d1c677d4af68ca9296c7cfa"
libc = "musl"
os = "linux"

    [[Conduit.download]]
    sha256 = "d56c9f3f47f25fca007f7c06e3567b123799e656787d2a07d20b1ea70595fae1"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.aarch64-linux-musl-cxx11.tar.gz"
[[Conduit]]
arch = "aarch64"
git-tree-sha1 = "d9484d5d4c28802d170d961902931a99cd432d40"
os = "freebsd"

    [[Conduit.download]]
    sha256 = "a7a777359f7fe7e008c6d1241f786d6d25a755aa1a53424d960181919d05073d"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.aarch64-unknown-freebsd.tar.gz"
[[Conduit]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21ca6c8f19874f6c995cb5aac18f2949f4e08d10"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "8f13d914ce96f357b14a488b00f69ad0711cd5bfcf4818b6d4fbff3ddac9d0b9"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Conduit]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53f4340091adcec8b4f86d6ddc7e317d332b2614"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "bf379ecce0b5c504320ea5001385c3f470f720d10399812ae31070882bf2ea6e"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Conduit]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0ed8323f2b3a25cec26095b775c66a9339c16541"
libc = "musl"
os = "linux"

    [[Conduit.download]]
    sha256 = "c31a74401520b8eb040fc819d55cc8fd196fc99df828fc4fa1c1ed29c49b08be"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Conduit]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48403923fb6b4886e6087da9bd957a12444c4378"
libc = "musl"
os = "linux"

    [[Conduit.download]]
    sha256 = "9fbe3e28e8b40cdf1aa60cbdac70cacff1ae226b6afa3c84159b9e384ff7da1d"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Conduit]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80a1a7c99f3f71817c023d4048b28b633475fab4"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "f9069db7f49a6ab243ea42df659103bb74343d82c3d82293f9a93ad973f5b53b"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Conduit]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d97e59d482dcaa9a08a96062af200dc5ee80ea3"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "e5471fce66dee3c2a7dfb3201fbccdd36a373557fa7d5a14d157b32ffb7a1b89"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Conduit]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d0a8d4f33dc8bc6446e76494b1ffe94325d621db"
libc = "musl"
os = "linux"

    [[Conduit.download]]
    sha256 = "672c8b25d1d707b8333e365fb94cb00cde9eedbb3dfb868f5c3ab971ecddc4fb"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Conduit]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1484d2a9a7e82b25741ef78e20c3cfe7ce9114c1"
libc = "musl"
os = "linux"

    [[Conduit.download]]
    sha256 = "5894838068b7cfac0af5b7f63b7fad88e5d21039f8845f5fb272052005edc922"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Conduit]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d5d04b9a328cc5f41615d0ff3c9988ac6ad50440"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "758f90cc4f40b3983738c156d22bf1f91c6b832ac891b3852de9efe7ed4095a1"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.i686-linux-gnu-cxx03.tar.gz"
[[Conduit]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d198b29e652ce1a986b58edcb30a0320e19752a4"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "99fb22a15356533f66e3218163db149ec3946b75f7d9ab72c21568a5eff87157"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.i686-linux-gnu-cxx11.tar.gz"
[[Conduit]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a26cf7cdad402e226683b8854f5ed73d1cb905f0"
libc = "musl"
os = "linux"

    [[Conduit.download]]
    sha256 = "4dbdd118baeed44f5b3e5b0f2450fa8c6025090c81bc2e0d18c9c34f0fa065dc"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.i686-linux-musl-cxx03.tar.gz"
[[Conduit]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "204941856a86ca25687dc9906fcf2af6ce8dd833"
libc = "musl"
os = "linux"

    [[Conduit.download]]
    sha256 = "d49f6e097e00bae52c81c77b4f8acc88b8b78c8c50999666961a38922db50726"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.i686-linux-musl-cxx11.tar.gz"
[[Conduit]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "798900caeea1747f6f44375ac9cddce8aa1b3a57"
os = "windows"

    [[Conduit.download]]
    sha256 = "9450cdffaff38090e92f7ec5095254456ab4e7884643e4a67d6d72053bbe5e80"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.i686-w64-mingw32-cxx03.tar.gz"
[[Conduit]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85ae1c0093f3627d0a6b099e9f4047bc1f66ef14"
os = "windows"

    [[Conduit.download]]
    sha256 = "dc10e5b41bbf9821735255e77a185d45447ffaaf5ca678e4289aa3811f4022f8"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.i686-w64-mingw32-cxx11.tar.gz"
[[Conduit]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7f6eb7f388be459752348a82147e3a9a7f5409bb"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "220ed32159a55ed43dcde045afc2904acc497c5ae9a60211b53bd90a1011e10b"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Conduit]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "565300e708f4500c3c31d190810073c69886886a"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "3dca6dbd624eeecc9906f4c7e18e41c46356b649420c761686984c89e4ef9766"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Conduit]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97e4087d701a6a2c7a0830bfda92b03f791874cd"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "ee03a8ecf0fadc0a965d1730718726cd0b4e09bfbfe873a656c5a491dfe684cc"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.riscv64-linux-gnu-cxx03.tar.gz"
[[Conduit]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a5c9f1e3734966ab0e1f50bbf7c120b3311d716"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "258412359d298e5cf77dcf3ac84b2d83f87e566aa5a7373488d931bd8c538783"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.riscv64-linux-gnu-cxx11.tar.gz"
[[Conduit]]
arch = "x86_64"
git-tree-sha1 = "bc2e4fefdd6b60853ee7ea3b778e863b0e2fb5de"
os = "macos"

    [[Conduit.download]]
    sha256 = "d6c9f8c49a19721c3e4fa6fcdef4b32bca3fc36c9332f0cc81563791dcfadb6d"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.x86_64-apple-darwin.tar.gz"
[[Conduit]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9cf5c935bd867ff81d13de0eedfa511aa9ca7da9"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "286cb73c1c64448f861b65e5d3c6a39ae78602cd0e6cbb596244ef01925c9b90"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.x86_64-linux-gnu-cxx03.tar.gz"
[[Conduit]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "404a4334e2a9a7bcbec70202896325a167a66073"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "593594270bb482e5cca6be2549351c3c5ebe26751de7e016361049bcee42f2e1"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.x86_64-linux-gnu-cxx11.tar.gz"
[[Conduit]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4602dfb4ca2c0826a84d437476fa7703948b55d0"
libc = "musl"
os = "linux"

    [[Conduit.download]]
    sha256 = "199a4b08f8f9e1c0e44138721f5c3b3699611a559a1097ec0dc6108dd5d2c348"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.x86_64-linux-musl-cxx03.tar.gz"
[[Conduit]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73f9b30100c32279838fcc451f524a6f5e481e67"
libc = "musl"
os = "linux"

    [[Conduit.download]]
    sha256 = "0bdc1c2d837fb2b11e9f38982d90af95194115f66d545e7a5b9e1f44c90cf671"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.x86_64-linux-musl-cxx11.tar.gz"
[[Conduit]]
arch = "x86_64"
git-tree-sha1 = "63318c2f4a6af8dd81ef3f5593827503320201db"
os = "freebsd"

    [[Conduit.download]]
    sha256 = "a82e587d6f3ca27f027e1f9a8fb2543f147ec606ed769ff03e4a3139d36be2b4"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.x86_64-unknown-freebsd.tar.gz"
[[Conduit]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee243876d41dfa6d46541626e9e0a87e10424f78"
os = "windows"

    [[Conduit.download]]
    sha256 = "a233332841e6bb55518a634f22b5eca3c05144c1ec25a7790bdab78e605165eb"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[Conduit]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c4036af4dd7a410785fde3e6736fe8e8e8ce536a"
os = "windows"

    [[Conduit.download]]
    sha256 = "5f3d6516d214ffe437556867661c28d271b4a3605400b3491154d2ff95f99b15"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.9.3+0/Conduit.v0.9.3.x86_64-w64-mingw32-cxx11.tar.gz"
