[[Conduit]]
arch = "aarch64"
git-tree-sha1 = "bb041938457fd92ee35155d90f23dc6c066f7fd4"
os = "macos"

    [[Conduit.download]]
    sha256 = "0ed0f5088828f12b979aab1497d3ff4d7c9deebae9b801b1031b19afc74dcd5e"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.aarch64-apple-darwin.tar.gz"
[[Conduit]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3bd68e913ad0ae7783b3e0318ec85d6888d04581"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "c3fbd659edf4c7c591ad3756d701284c112c0c166a1179d237e18805f3d83285"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Conduit]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "919fdd881954e00c870fb6c3b9b72da9e5b8878e"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "30974dae3c0c6e00743e3904513b4ee3b0df436a88c00ec856fa1583cf3dec8d"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Conduit]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "07688fb2a28ad2e3e2019d3483fb60966e0a95f9"
libc = "musl"
os = "linux"

    [[Conduit.download]]
    sha256 = "c0f1d4ae74c9acc9eddf0898c37e5c728dda72f3999bf212344fe58159e6f9f1"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.aarch64-linux-musl-cxx03.tar.gz"
[[Conduit]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "745cdc9514f8580d8389830629b7ca7eda60f1c7"
libc = "musl"
os = "linux"

    [[Conduit.download]]
    sha256 = "acaa13d4c8d6bf4df57d70a10e7206d926b07e0893f89da7a5fef8f59d49648c"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.aarch64-linux-musl-cxx11.tar.gz"
[[Conduit]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f4011904ce0b87cb6c450c1f274abdd7a78b8485"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "d8a94e485ea317ccd44f12986c6a9c70a1d907109a361c0c8ea664db5f2f96d0"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Conduit]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1275787f4edfc95cb634089ceae46a42ec607a52"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "cd25941e9455d864c18d4406d8dea10bcdf5c5edd1b52d551d5c8c932002cc0f"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Conduit]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "456bb93b930b1e5eabf2be21c600c9650b467e94"
libc = "musl"
os = "linux"

    [[Conduit.download]]
    sha256 = "8019fff8bdf08b58eb723ff2f7b0604e3d2427905227475dcfbb5de0be062755"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Conduit]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4362c044a4a912dce776857631b2e3639032258a"
libc = "musl"
os = "linux"

    [[Conduit.download]]
    sha256 = "89322f81ff15db19a65b2b0acd15cc3104c9c796307aa3ae12935eec22b668cd"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Conduit]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7cfc7d222508a0ce2e42586b43ad62b0a434ba1a"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "5dfa9406ed80ae030d13fb611335156e2bf30d54f457f1379fd1938673b9e8e7"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Conduit]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e5d768915ea7d61b3e21fc8131d82bbd6a91b9a"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "9d914ee8de53f4d986b32ee4604aba77629cd7c9dbddf137bc9b0b9eb04ba7e0"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Conduit]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0fc68ae368c5d9cfb81a5ab66720c25c40be4665"
libc = "musl"
os = "linux"

    [[Conduit.download]]
    sha256 = "751d58895dcbc4fd885d111d4fbb1d567605c31ca894c08b4a5eb9f3c1dc8a4b"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Conduit]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3cdf0c75ec6b629e34b003d97cbe7f1df394d6f2"
libc = "musl"
os = "linux"

    [[Conduit.download]]
    sha256 = "1a4090ce84256c7383148f82c3c4ec42e1fb09fac2332f9486092a4e09067c4f"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Conduit]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "966faf327e677584aa1e55e6f93e92df15d6c04f"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "03188d4eea8bf922dcf16187f82fb0ccab8f359cf968a0815076e7231a1392dd"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.i686-linux-gnu-cxx03.tar.gz"
[[Conduit]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "73ae2297e9417c229e7903f18d394bce27f64cea"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "c6d727f02310c166ae92de65ddd0cb148f436222d232ad5e69dbd76a54ad8e41"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.i686-linux-gnu-cxx11.tar.gz"
[[Conduit]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aee381b1b797c1ef41573501df0c6ff3cab67229"
libc = "musl"
os = "linux"

    [[Conduit.download]]
    sha256 = "606f47c92caf1ede33507c902d65c2ab1d933dc205e369cec640d8b92421dd3f"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.i686-linux-musl-cxx03.tar.gz"
[[Conduit]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19617167a6ca5875475955fa8f2cf0435ecea056"
libc = "musl"
os = "linux"

    [[Conduit.download]]
    sha256 = "2ca85f948fc3ae36af8b90950aebf3f8e3a4bfff21898e278cec6a1d5551a572"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.i686-linux-musl-cxx11.tar.gz"
[[Conduit]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb1b0d49d5b21ef8c6d3c407dfbbc38e3ce6cd50"
os = "windows"

    [[Conduit.download]]
    sha256 = "dbfcac26b28b6453f4af06191e259a43a7025d27508e8f5e780a18c90da0face"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.i686-w64-mingw32-cxx03.tar.gz"
[[Conduit]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c34a40761943bb7965d7aac516b0b0d26ac2c4a"
os = "windows"

    [[Conduit.download]]
    sha256 = "729d3760b35af944dd6e74d09e84a22ff6358c032d56d2df10ba68b408bd27b6"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.i686-w64-mingw32-cxx11.tar.gz"
[[Conduit]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a42f00600fc54e000cb8038ba1f2f9e2f9384398"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "b3d93bdc2b97eccfce720ec509980f1d8d57934c009a9a8db3c5d982a20be68e"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Conduit]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9bf1be9d1ec0cab8ad6a00827252c4d632a709b"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "d49be6d5671bd58ceefb05bcbe13b101c6d6d1e3418f32e20ec05ad7e6a2b6e2"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Conduit]]
arch = "x86_64"
git-tree-sha1 = "e9a8dc294a64ac8bc663572a263bf8cdcc467564"
os = "macos"

    [[Conduit.download]]
    sha256 = "7f32dbf07d721145b97b2aa89cb8709a3623218b4fb0a6df2169bb355a829556"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.x86_64-apple-darwin.tar.gz"
[[Conduit]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d19d09a2923a744d7ed3f924a104ed675664e247"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "a1dac818397dfb2f510cfa31b2b05866b5e96e0c07c0afb490d7b17a01801c91"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Conduit]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87f95dde6798d02d8122bd95ec50252d96031eb2"
libc = "glibc"
os = "linux"

    [[Conduit.download]]
    sha256 = "3a46ca29355f860f44ff53a87e3af6d03374abfba6451a60f25167839f611e3d"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Conduit]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "925ee695ab257942898408db3ef5a79e82d036b7"
libc = "musl"
os = "linux"

    [[Conduit.download]]
    sha256 = "ce1adf8aa7f38816a0b80fd31689571e701fcd148eaef9430c768cd8efaa7810"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.x86_64-linux-musl-cxx03.tar.gz"
[[Conduit]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c570cc3f367926e6339bc90013aebae63c230f1"
libc = "musl"
os = "linux"

    [[Conduit.download]]
    sha256 = "3f9cdde9829d965018e0fe35dd55021eb2a2354556a4a3c6b4d9f4f746764773"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.x86_64-linux-musl-cxx11.tar.gz"
[[Conduit]]
arch = "x86_64"
git-tree-sha1 = "31201ba8e64d6e2706f1b759f25fefa10a265019"
os = "freebsd"

    [[Conduit.download]]
    sha256 = "b63f4a02acd0d0efb063a871fee37b0419916b77bcb1ca8baedd4cfb28afe089"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.x86_64-unknown-freebsd.tar.gz"
[[Conduit]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d0c9ccd08d07bd0f1e6ec4d13d7f134dbf34fe7"
os = "windows"

    [[Conduit.download]]
    sha256 = "355e0c3d97f49f68484b84f3defb35580f44846d15b01bd139a839717ea33e5f"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Conduit]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0798f3449e9b6a50387e88a2c632e5ee7a85b49a"
os = "windows"

    [[Conduit.download]]
    sha256 = "5dff2ef67453e144729bd192f40f43e3ba4fa5ca3a609c3028e16a1a16dd6de8"
    url = "https://github.com/JuliaBinaryWrappers/Conduit_jll.jl/releases/download/Conduit-v0.8.1+0/Conduit.v0.8.1.x86_64-w64-mingw32-cxx11.tar.gz"
