# Autogenerated wrapper script for Conduit_jll for aarch64-apple-darwin-mpi+mpitrampoline
export conduit_adjset_validate, conduit_blueprint_verify, conduit_generate_data, conduit_relay_io_convert, conduit_relay_io_ls, libconduit, libconduit_blueprint, libconduit_relay

using LLVMOpenMP_jll
using HDF5_jll
using Zlib_jll
using zfp_jll
using MPItrampoline_jll
JLLWrappers.@generate_wrapper_header("Conduit")
JLLWrappers.@declare_library_product(libconduit, "@rpath/libconduit.dylib")
JLLWrappers.@declare_library_product(libconduit_blueprint, "@rpath/libconduit_blueprint.dylib")
JLLWrappers.@declare_library_product(libconduit_relay, "@rpath/libconduit_relay.dylib")
JLLWrappers.@declare_executable_product(conduit_adjset_validate)
JLLWrappers.@declare_executable_product(conduit_blueprint_verify)
JLLWrappers.@declare_executable_product(conduit_generate_data)
JLLWrappers.@declare_executable_product(conduit_relay_io_convert)
JLLWrappers.@declare_executable_product(conduit_relay_io_ls)
function __init__()
    JLLWrappers.@generate_init_header(LLVMOpenMP_jll, HDF5_jll, Zlib_jll, zfp_jll, MPItrampoline_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libconduit,
        "lib/libconduit.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libconduit_blueprint,
        "lib/libconduit_blueprint.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libconduit_relay,
        "lib/libconduit_relay.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        conduit_adjset_validate,
        "bin/conduit_adjset_validate",
    )

    JLLWrappers.@init_executable_product(
        conduit_blueprint_verify,
        "bin/conduit_blueprint_verify",
    )

    JLLWrappers.@init_executable_product(
        conduit_generate_data,
        "bin/conduit_generate_data",
    )

    JLLWrappers.@init_executable_product(
        conduit_relay_io_convert,
        "bin/conduit_relay_io_convert",
    )

    JLLWrappers.@init_executable_product(
        conduit_relay_io_ls,
        "bin/conduit_relay_io_ls",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
