# Autogenerated wrapper script for Conduit_jll for i686-w64-mingw32-cxx03-mpi+microsoftmpi
export conduit_adjset_validate, conduit_blueprint_verify, conduit_generate_data, conduit_relay_io_convert, conduit_relay_io_ls, libconduit, libconduit_blueprint, libconduit_relay

using CompilerSupportLibraries_jll
using HDF5_jll
using Zlib_jll
using zfp_jll
using MicrosoftMPI_jll
JLLWrappers.@generate_wrapper_header("Conduit")
JLLWrappers.@declare_library_product(libconduit, "libconduit.dll")
JLLWrappers.@declare_library_product(libconduit_blueprint, "libconduit_blueprint.dll")
JLLWrappers.@declare_library_product(libconduit_relay, "libconduit_relay.dll")
JLLWrappers.@declare_executable_product(conduit_adjset_validate)
JLLWrappers.@declare_executable_product(conduit_blueprint_verify)
JLLWrappers.@declare_executable_product(conduit_generate_data)
JLLWrappers.@declare_executable_product(conduit_relay_io_convert)
JLLWrappers.@declare_executable_product(conduit_relay_io_ls)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, HDF5_jll, Zlib_jll, zfp_jll, MicrosoftMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libconduit,
        "bin\\libconduit.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libconduit_blueprint,
        "bin\\libconduit_blueprint.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libconduit_relay,
        "bin\\libconduit_relay.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        conduit_adjset_validate,
        "bin\\conduit_adjset_validate.exe",
    )

    JLLWrappers.@init_executable_product(
        conduit_blueprint_verify,
        "bin\\conduit_blueprint_verify.exe",
    )

    JLLWrappers.@init_executable_product(
        conduit_generate_data,
        "bin\\conduit_generate_data.exe",
    )

    JLLWrappers.@init_executable_product(
        conduit_relay_io_convert,
        "bin\\conduit_relay_io_convert.exe",
    )

    JLLWrappers.@init_executable_product(
        conduit_relay_io_ls,
        "bin\\conduit_relay_io_ls.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
