# Autogenerated wrapper script for Conduit_jll for x86_64-apple-darwin
export libconduit, libconduit_blueprint, libconduit_relay

using Zlib_jll
using zfp_jll
JLLWrappers.@generate_wrapper_header("Conduit")
JLLWrappers.@declare_library_product(libconduit, "@rpath/libconduit.dylib")
JLLWrappers.@declare_library_product(libconduit_blueprint, "@rpath/libconduit_blueprint.dylib")
JLLWrappers.@declare_library_product(libconduit_relay, "@rpath/libconduit_relay.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, zfp_jll)
    JLLWrappers.@init_library_product(
        libconduit,
        "lib/libconduit.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libconduit_blueprint,
        "lib/libconduit_blueprint.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libconduit_relay,
        "lib/libconduit_relay.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
